### PR TITLE
AmazonSNS service maximum message size

### LINKED ISSUE #1091: Amazon SNS messages too large
# Problem

We've run into an issue recently where an Amazon SNS hook for a repo sent a push event message that was too large (333K), SNS messages have a [maximum size of 256K](https://docs.aws.amazon.com/sns/latest/dg/large-payload-raw-message.html). We have an internal application that listens to events for a number of our company's repos and relays the messages through SNS. The application has missed a number of events because of this unexpected interaction between the SNS message size limit and Github. Missed events have caused a number of subtle bugs in our application that went unnoticed until now.

# Possible Solution

Check the size of an SNS message before sending it. If the size exceeds 256K, send some form of error message explaining that the message size exceeded 256K and include a url to the actual event. This would shift the responsibility to the client to get the event from github and process it.

### PR DESCRIPTION
**Pull request by Rostepher**
# Purpose

[`Service::AmazonSNS#publish_to_sns`](https://github.com/hudl/github-services/blob/54c1d7ff78b55bea788c7c0ddc4d60e5f457f295/lib/services/amazon_sns.rb#L37) now checks for the maximum message size of 256K. If the message exceeds the maximum size, it will split the payload into parts with some ordering information and an md5 digest of the original payload.

Resolves #1091

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Nice approach! Can you agree to the CLA? Also, I'll let @kdaigle :eyes: this too. Thanks so much!

File: lib/services/amazon_sns.rb [hunk 1]
```diff
@@ -35,17 +42,43 @@ def publish_to_sns(cfg, json)
...
-      raise_missing_error e.message
-    rescue SocketError
-      raise_missing_error
+      if json.bytesize <= MAX_MESSAGE_SIZE
+        sns.publish({
+          :message            => json,
+          :topic_arn          => cfg['sns_topic'],
+          :message_attributes => message_attributes
+        })
+      end
```
Comment (kdaigle) [inline lib/services/amazon_sns.rb]: Slightly confused. If the message is less than the maximum size, shouldn't we just send that *one* message and be done? The `if end` here will still try to do the second set of messages below.

We also want to make sure the `rescue`s below work for either. I may be worth building a helper method that does the `sns.publish` to clean up the code a fair bit.

**Comment by kdaigle** [comment]
@Rostepher thanks for opening a PR! Could you also update the tests for this approach? There are a few code concerns and refactoring we should probably do but a few tests will help make that a lot easier as well.

**Comment by Rostepher** [comment]
@kdaigle I'll make the suggested changes today. As for testing, it doesn't look like `Service::AmazonSNS#publish_to_sns` was every properly tested. @mikemcquaid I agreed to the Github CLA yesterday when I made this PR, it doesn't seem to have updated yet, possibly a bug?

**Comment by mikemcquaid** [comment]
@Rostepher Weird. Can you try and click through and agree again, just to humour me? Thanks!

**Comment by Rostepher** [comment]
@mikemcquaid I don't have the option to agree to the CLA.
screen shot 2015-11-13 at 11 23 46 am

**Comment by mikemcquaid** [comment]
No worries, thanks!

**Comment by Rostepher** [comment]
@mikemcquaid @kdaigle I've updated the code, it fails the new test cases with an AWS error: `Aws::SNS::Errors::InvalidClientTokenId: The security token included in the request is invalid.` I'm guessing the token just needs to be updated.

**Comment by damtur** [comment]
Hey, can I please bump this up, as we really would like this PR to happen, and in our opinions tests are failing not because of us.

**Comment by mikemcquaid** [comment]
@damtur Please be patient, we'll get to this as soon as we can, thanks!

**Comment by kdaigle** [comment]
We're going to have to figure out the best way to get these tests passing. It's not a great idea to actually have these credentials in the repository (even if we updated them to work). I believe your tests just showed that we we weren't actually hitting Amazon correctly.

The best case scenario is we'd create a stub for the AWS Client and check that it's getting called with the correct arguments. Is that something you could tackle @Rostepher? Sorry for the delay in getting back to you. :smile:

**Comment by damtur** [comment]
Hey @kdaigle, thanks for your response. Unfortunately we are reluctant to fix those tests as those are not related with our fix at all and we don't want to dig through the code as we are not sure how deep those fixes will be. 
Moreover on daily basis we are not using Ruby so it's a big hustle for us to fix those.
And those tests are not failing because of our change so those should be done in separate PR imo.
I suggest merging in our change as soon as you test it manually, and then creating a new issue which will deal with those failing tests.
Thx!

**Comment by mikemcquaid** [comment]
> Hey @kdaigle, thanks for your response. Unfortunately we are reluctant to fix those tests as those are not related with our fix at all and we don't want to dig through the code as we are not sure how deep those fixes will be. 
> Moreover on daily basis we are not using Ruby so it's a big hustle for us to fix those.
> And those tests are not failing because of our change so those should be done in separate PR imo.
> I suggest merging in our change as soon as you test it manually, and then creating a new issue which will deal with those failing tests.

Hi @damtur! Ideally these tests would be already green before this PR, I agree. However, as they aren't, it would be great if you could try to make the test fixes @kdaigle suggested so this PR is green. Although you have no obligation to do so it will make it easier for us to merge this change and future contributors to submit PRs if you can do so. If you can't it may take longer for this PR to get merged. Sorry and thanks again!

**Comment by mikemcquaid** [comment]
@damtur Any thoughts on my comment above?

**Comment by mikemcquaid** [comment]
To clarify further here: [`master` is passing](https://travis-ci.org/github/github-services) so the test failure in this PR is because of the changes in this PR so they'll need to be fixed for this to be merged (we can't commit to your PR branch).

**Comment by mikemcquaid** [comment]
Thinking about this more if @kdaigle is :ok: I'd be alright with commenting those tests out and adding an explanation as for why and, as long as the rest of the tests are passing, merging this as-is.

**Comment by damtur** [comment]
Thank you @mikemcquaid for response. Unfortunately we don't have manpower to fix those tests, so ideally your solution with commenting out them for now would be a way to go. Waiting for @kdaigle and we'll prepare an update to code.

**Comment by mikemcquaid** [comment]
@damtur If you could comment those tests out for now that'd be good. If @kdaigle doesn't agree: I'll work on this myself in another PR. Thanks for all your work here :sparkles:

**Comment by mikemcquaid** [comment]
@damtur Actually, @kdaigle has given me a :+1: in Chat but my smart coworker @jasonrudolph suggested that using `skip "some useful comment about why this test is being skipped"` would be nicer than commenting them out. Once we have that: I'll merge. Thanks again!

**Comment by mikemcquaid** [comment]
@damtur @Rostepher Any news on this? Hoping to get this merged in or closed out soon. Thanks!

**Comment by mikemcquaid** [comment]
@damtur @Rostepher Gentle ping on this again?

**Comment by damtur** [comment]
@mikemcquaid I'm sorry for delay. @Rostepher is no longer working for Hudl, and I have problems with my GitHub notifications and haven't seen update on that.

Now tests are passing. Thank you for all your assistance and patience.

**Comment by mikemcquaid** [comment]
Thanks @damtur and @Rostepher. This was deployed to production.
