### PR TITLE
autodeploy: fix some bugs.

### LINKED ISSUE #1046: auto-deploy service doesn't correctly handle pushes to branches which have a slash in their name
Currently, the default branch is fetched like [this](https://github.com/github/github-services/blob/4419bac3adb3fb7fa0158b94ee45d56600522f2d/lib/services/auto_deploy.rb#L55-L57):

```
def default_branch
    payload['repository']['default_branch']
end
```

However, the branch which was pushed to is fetched like [this](https://github.com/github/github-services/blob/4419bac3adb3fb7fa0158b94ee45d56600522f2d/lib/services/auto_deploy.rb#L35-L37):

```
def payload_ref
    payload['ref'].split('/').last
end
```

So, if the `ref` from the payload is `refs/heads/foo/bar`, the `payload_ref` method would return `bar` instead of `foo/bar`. If `foo/bar` is the default branch, then [this check](https://github.com/github/github-services/blob/4419bac3adb3fb7fa0158b94ee45d56600522f2d/lib/services/auto_deploy.rb#L59-L61) will fail and a deployment won't be created.

Maybe [this approach](https://github.com/github/github-services/blob/4419bac3adb3fb7fa0158b94ee45d56600522f2d/lib/services/you_track.rb#L38) would be a better approach for `payload_ref`?

cc @github/hooks

### LINKED ISSUE #1129: auto-deploy service doesn't use status_contexts
Currently, the UI for the autodeploy hook allows you to provide a comma separated list of status_contexts that should be green for an auto deployment to happen. Currently, this field isn't used at all in https://github.com/github/github-services/blob/master/lib/services/auto_deploy.rb and a deployment will be triggered on _any_ green status update.

The behavior I would expected would be to be able to provide multiple status contexts and only have an auto deploy triggered when all status contexts turn green.

This field has been in the UI for going on a year now with no implementation. Is this hook going to be maintained by someone at github moving forward?

### PR DESCRIPTION
**Pull request by mikemcquaid**
- Don’t show status_contexts as it doesn’t actually do anything.
- Correctly handle the payload ref.

CC @izuzak @ejholmes @kdaigle 

Closes #1046.
Closes #1129.

### CODE REVIEW

**Comment by bswinnerton** [comment]
👍  , this looks good to me @mikemcquaid. I'd wait for a second set of 👀  from one of the people you've CC'd in case there is any historical context I'm missing.

File: lib/services/auto_deploy.rb [hunk 1]
```diff
@@ -33,7 +32,7 @@ def environment_names
   end
 
   def payload_ref
-    payload['ref'].split('/').last
+    payload['ref'].to_s[/refs\/heads\/(.*)/, 1]
```
Comment (kdaigle) [inline lib/services/auto_deploy.rb]: A test for this would make me feel more confident this change won't adversely impact existing installs.

Comment (mikemcquaid) [inline lib/services/auto_deploy.rb]: Added.
